bundle update middleman-autoprefixer
To fix

```
ERROR NoMethodError: undefined method 'bytesize' for Rack::Utils:Module
```

when upgrading to middleman v4.